export interface ComponentDescriptor {
  name: string;
  tag: string;
  pkg: string;
  source: string;
  css?: string;
  className?: string;
}

// 51 Carbon Web Components
export const CARBON_COMPONENTS: ComponentDescriptor[] = [
  { name: 'accordion', tag: 'cds-accordion', pkg: '@carbon/web-components', source: 'es/components/accordion/accordion.js', css: 'es/components/accordion/accordion.scss.js' },
  { name: 'accordion-item', tag: 'cds-accordion-item', pkg: '@carbon/web-components', source: 'es/components/accordion/accordion-item.js', css: 'es/components/accordion/accordion.scss.js' },
  { name: 'breadcrumb', tag: 'cds-breadcrumb', pkg: '@carbon/web-components', source: 'es/components/breadcrumb/breadcrumb.js', css: 'es/components/breadcrumb/breadcrumb.scss.js' },
  { name: 'breadcrumb-item', tag: 'cds-breadcrumb-item', pkg: '@carbon/web-components', source: 'es/components/breadcrumb/breadcrumb-item.js', css: 'es/components/breadcrumb/breadcrumb.scss.js' },
  { name: 'button', tag: 'cds-button', pkg: '@carbon/web-components', source: 'es/components/button/button.js', css: 'es/components/button/button.scss.js' },
  { name: 'checkbox', tag: 'cds-checkbox', pkg: '@carbon/web-components', source: 'es/components/checkbox/checkbox.js', css: 'es/components/checkbox/checkbox.scss.js' },
  { name: 'code-snippet', tag: 'cds-code-snippet', pkg: '@carbon/web-components', source: 'es/components/code-snippet/code-snippet.js', css: 'es/components/code-snippet/code-snippet.scss.js' },
  { name: 'combo-box', tag: 'cds-combo-box', pkg: '@carbon/web-components', source: 'es/components/combo-box/combo-box.js', css: 'es/components/combo-box/combo-box.scss.js' },
  {
    name: 'content-switcher',
    tag: 'cds-content-switcher',
    pkg: '@carbon/web-components',
    source: 'es/components/content-switcher/content-switcher.js',
    css: 'es/components/content-switcher/content-switcher.scss.js',
  },
  {
    name: 'content-switcher-item',
    tag: 'cds-content-switcher-item',
    pkg: '@carbon/web-components',
    source: 'es/components/content-switcher/content-switcher-item.js',
    css: 'es/components/content-switcher/content-switcher.scss.js',
  },
  { name: 'copy-button', tag: 'cds-copy-button', pkg: '@carbon/web-components', source: 'es/components/copy-button/copy-button.js', css: 'es/components/copy-button/copy-button.scss.js' },
  { name: 'data-table', tag: 'cds-data-table', pkg: '@carbon/web-components', source: 'es/components/data-table/table.js', css: 'es/components/data-table/data-table.scss.js' },
  { name: 'date-picker', tag: 'cds-date-picker', pkg: '@carbon/web-components', source: 'es/components/date-picker/date-picker.js', css: 'es/components/date-picker/date-picker.scss.js' },
  { name: 'dropdown', tag: 'cds-dropdown', pkg: '@carbon/web-components', source: 'es/components/dropdown/dropdown.js', css: 'es/components/dropdown/dropdown.scss.js' },
  { name: 'dropdown-item', tag: 'cds-dropdown-item', pkg: '@carbon/web-components', source: 'es/components/dropdown/dropdown-item.js', css: 'es/components/dropdown/dropdown.scss.js' },
  { name: 'file-uploader', tag: 'cds-file-uploader', pkg: '@carbon/web-components', source: 'es/components/file-uploader/file-uploader.js', css: 'es/components/file-uploader/file-uploader.scss.js' },
  { name: 'form-group', tag: 'cds-form-group', pkg: '@carbon/web-components', source: 'es/components/form-group/form-group.js', css: 'es/components/form-group/form-group.scss.js' },
  {
    name: 'inline-loading',
    tag: 'cds-inline-loading',
    pkg: '@carbon/web-components',
    source: 'es/components/inline-loading/inline-loading.js',
    css: 'es/components/inline-loading/inline-loading.scss.js',
  },
  { name: 'link', tag: 'cds-link', pkg: '@carbon/web-components', source: 'es/components/link/link.js', css: 'es/components/link/link.scss.js' },
  { name: 'loading', tag: 'cds-loading', pkg: '@carbon/web-components', source: 'es/components/loading/loading.js', css: 'es/components/loading/loading.scss.js' },
  { name: 'modal', tag: 'cds-modal', pkg: '@carbon/web-components', source: 'es/components/modal/modal.js', css: 'es/components/modal/modal.scss.js' },
  { name: 'modal-body', tag: 'cds-modal-body', pkg: '@carbon/web-components', source: 'es/components/modal/modal-body.js', css: 'es/components/modal/modal.scss.js' },
  { name: 'modal-header', tag: 'cds-modal-header', pkg: '@carbon/web-components', source: 'es/components/modal/modal-header.js', css: 'es/components/modal/modal.scss.js' },
  { name: 'modal-footer', tag: 'cds-modal-footer', pkg: '@carbon/web-components', source: 'es/components/modal/modal-footer.js', css: 'es/components/modal/modal.scss.js' },
  { name: 'multi-select', tag: 'cds-multi-select', pkg: '@carbon/web-components', source: 'es/components/multi-select/multi-select.js', css: 'es/components/multi-select/multi-select.scss.js' },
  {
    name: 'notification',
    tag: 'cds-inline-notification',
    pkg: '@carbon/web-components',
    source: 'es/components/notification/inline-notification.js',
    css: 'es/components/notification/inline-notification.scss.js',
  },
  {
    name: 'toast-notification',
    tag: 'cds-toast-notification',
    pkg: '@carbon/web-components',
    source: 'es/components/notification/toast-notification.js',
    css: 'es/components/notification/toast-notification.scss.js',
  },
  { name: 'number-input', tag: 'cds-number-input', pkg: '@carbon/web-components', source: 'es/components/number-input/number-input.js', css: 'es/components/number-input/number-input.scss.js' },
  { name: 'overflow-menu', tag: 'cds-overflow-menu', pkg: '@carbon/web-components', source: 'es/components/overflow-menu/overflow-menu.js', css: 'es/components/overflow-menu/overflow-menu.scss.js' },
  {
    name: 'overflow-menu-body',
    tag: 'cds-overflow-menu-body',
    pkg: '@carbon/web-components',
    source: 'es/components/overflow-menu/overflow-menu-body.js',
    css: 'es/components/overflow-menu/overflow-menu.scss.js',
  },
  {
    name: 'overflow-menu-item',
    tag: 'cds-overflow-menu-item',
    pkg: '@carbon/web-components',
    source: 'es/components/overflow-menu/overflow-menu-item.js',
    css: 'es/components/overflow-menu/overflow-menu.scss.js',
  },
  { name: 'pagination', tag: 'cds-pagination', pkg: '@carbon/web-components', source: 'es/components/pagination/pagination.js', css: 'es/components/pagination/pagination.scss.js' },
  { name: 'popover', tag: 'cds-popover', pkg: '@carbon/web-components', source: 'es/components/popover/popover.js', css: 'es/components/popover/popover.scss.js' },
  { name: 'popover-content', tag: 'cds-popover-content', pkg: '@carbon/web-components', source: 'es/components/popover/popover-content.js', css: 'es/components/popover/popover.scss.js' },
  { name: 'progress-bar', tag: 'cds-progress-bar', pkg: '@carbon/web-components', source: 'es/components/progress-bar/progress-bar.js', css: 'es/components/progress-bar/progress-bar.scss.js' },
  {
    name: 'progress-indicator',
    tag: 'cds-progress-indicator',
    pkg: '@carbon/web-components',
    source: 'es/components/progress-indicator/progress-indicator.js',
    css: 'es/components/progress-indicator/progress-indicator.scss.js',
  },
  { name: 'radio-button', tag: 'cds-radio-button', pkg: '@carbon/web-components', source: 'es/components/radio-button/radio-button.js', css: 'es/components/radio-button/radio-button.scss.js' },
  {
    name: 'radio-button-group',
    tag: 'cds-radio-button-group',
    pkg: '@carbon/web-components',
    source: 'es/components/radio-button/radio-button-group.js',
    css: 'es/components/radio-button/radio-button.scss.js',
  },
  { name: 'search', tag: 'cds-search', pkg: '@carbon/web-components', source: 'es/components/search/search.js', css: 'es/components/search/search.scss.js' },
  { name: 'select', tag: 'cds-select', pkg: '@carbon/web-components', source: 'es/components/select/select.js', css: 'es/components/select/select.scss.js' },
  { name: 'tile', tag: 'cds-tile', pkg: '@carbon/web-components', source: 'es/components/tile/tile.js', css: 'es/components/tile/tile.scss.js' },
  { name: 'skeleton-text', tag: 'cds-skeleton-text', pkg: '@carbon/web-components', source: 'es/components/skeleton-text/skeleton-text.js', css: 'es/components/skeleton-text/skeleton-text.scss.js' },
  {
    name: 'skeleton-placeholder',
    tag: 'cds-skeleton-placeholder',
    pkg: '@carbon/web-components',
    source: 'es/components/skeleton-placeholder/skeleton-placeholder.js',
    css: 'es/components/skeleton-placeholder/skeleton-placeholder.scss.js',
  },
  { name: 'slider', tag: 'cds-slider', pkg: '@carbon/web-components', source: 'es/components/slider/slider.js', css: 'es/components/slider/slider.scss.js' },
  {
    name: 'structured-list',
    tag: 'cds-structured-list',
    pkg: '@carbon/web-components',
    source: 'es/components/structured-list/structured-list.js',
    css: 'es/components/structured-list/structured-list.scss.js',
  },
  { name: 'tabs', tag: 'cds-tabs', pkg: '@carbon/web-components', source: 'es/components/tabs/tabs.js', css: 'es/components/tabs/tabs.scss.js' },
  { name: 'tab', tag: 'cds-tab', pkg: '@carbon/web-components', source: 'es/components/tabs/tab.js', css: 'es/components/tabs/tabs.scss.js' },
  { name: 'tag', tag: 'cds-tag', pkg: '@carbon/web-components', source: 'es/components/tag/tag.js', css: 'es/components/tag/tag.scss.js' },
  { name: 'text-input', tag: 'cds-text-input', pkg: '@carbon/web-components', source: 'es/components/text-input/text-input.js', css: 'es/components/text-input/text-input.scss.js' },
  { name: 'textarea', tag: 'cds-textarea', pkg: '@carbon/web-components', source: 'es/components/textarea/textarea.js', css: 'es/components/textarea/textarea.scss.js' },
  { name: 'toggle', tag: 'cds-toggle', pkg: '@carbon/web-components', source: 'es/components/toggle/toggle.js', css: 'es/components/toggle/toggle.scss.js' },
];

// 51 Spectrum Web Components
export const SPECTRUM_COMPONENTS: ComponentDescriptor[] = [
  { name: 'accordion', tag: 'sp-accordion', pkg: '@spectrum-web-components', source: 'accordion/src/Accordion.js', css: 'accordion/src/accordion.css.js' },
  { name: 'accordion-item', tag: 'sp-accordion-item', pkg: '@spectrum-web-components', source: 'accordion/src/AccordionItem.js', css: 'accordion/src/accordion-item.css.js' },
  { name: 'action-bar', tag: 'sp-action-bar', pkg: '@spectrum-web-components', source: 'action-bar/src/ActionBar.js', css: 'action-bar/src/action-bar.css.js' },
  { name: 'action-button', tag: 'sp-action-button', pkg: '@spectrum-web-components', source: 'action-button/src/ActionButton.js', css: 'action-button/src/action-button.css.js' },
  { name: 'action-group', tag: 'sp-action-group', pkg: '@spectrum-web-components', source: 'action-group/src/ActionGroup.js', css: 'action-group/src/action-group.css.js' },
  { name: 'action-menu', tag: 'sp-action-menu', pkg: '@spectrum-web-components', source: 'action-menu/src/ActionMenu.js', css: 'action-menu/src/action-menu.css.js' },
  { name: 'asset', tag: 'sp-asset', pkg: '@spectrum-web-components', source: 'asset/src/Asset.js', css: 'asset/src/asset.css.js' },
  { name: 'avatar', tag: 'sp-avatar', pkg: '@spectrum-web-components', source: 'avatar/src/Avatar.js', css: 'avatar/src/avatar.css.js' },
  { name: 'badge', tag: 'sp-badge', pkg: '@spectrum-web-components', source: 'badge/src/Badge.js', css: 'badge/src/badge.css.js' },
  { name: 'toast', tag: 'sp-toast', pkg: '@spectrum-web-components', source: 'toast/src/Toast.js', css: 'toast/src/toast.css.js' },
  { name: 'button', tag: 'sp-button', pkg: '@spectrum-web-components', source: 'button/src/Button.js', css: 'button/src/button.css.js' },
  { name: 'button-group', tag: 'sp-button-group', pkg: '@spectrum-web-components', source: 'button-group/src/ButtonGroup.js', css: 'button-group/src/button-group.css.js' },
  { name: 'card', tag: 'sp-card', pkg: '@spectrum-web-components', source: 'card/src/Card.js', css: 'card/src/card.css.js' },
  { name: 'checkbox', tag: 'sp-checkbox', pkg: '@spectrum-web-components', source: 'checkbox/src/Checkbox.js', css: 'checkbox/src/checkbox.css.js' },
  { name: 'table', tag: 'sp-table', pkg: '@spectrum-web-components', source: 'table/src/Table.js', css: 'table/src/table.css.js' },
  { name: 'tray', tag: 'sp-tray', pkg: '@spectrum-web-components', source: 'tray/src/Tray.js', css: 'tray/src/tray.css.js' },
  { name: 'underlay', tag: 'sp-underlay', pkg: '@spectrum-web-components', source: 'underlay/src/Underlay.js', css: 'underlay/src/underlay.css.js' },
  { name: 'coachmark', tag: 'sp-coachmark', pkg: '@spectrum-web-components', source: 'coachmark/src/Coachmark.js', css: 'coachmark/src/coachmark.css.js' },
  { name: 'color-area', tag: 'sp-color-area', pkg: '@spectrum-web-components', source: 'color-area/src/ColorArea.js', css: 'color-area/src/color-area.css.js' },
  { name: 'color-field', tag: 'sp-color-field', pkg: '@spectrum-web-components', source: 'color-field/src/ColorField.js', css: 'color-field/src/color-field.css.js' },
  { name: 'color-handle', tag: 'sp-color-handle', pkg: '@spectrum-web-components', source: 'color-handle/src/ColorHandle.js', css: 'color-handle/src/color-handle.css.js' },
  { name: 'color-loupe', tag: 'sp-color-loupe', pkg: '@spectrum-web-components', source: 'color-loupe/src/ColorLoupe.js', css: 'color-loupe/src/color-loupe.css.js' },
  { name: 'color-slider', tag: 'sp-color-slider', pkg: '@spectrum-web-components', source: 'color-slider/src/ColorSlider.js', css: 'color-slider/src/color-slider.css.js' },
  { name: 'color-wheel', tag: 'sp-color-wheel', pkg: '@spectrum-web-components', source: 'color-wheel/src/ColorWheel.js', css: 'color-wheel/src/color-wheel.css.js' },
  { name: 'dialog', tag: 'sp-dialog', pkg: '@spectrum-web-components', source: 'dialog/src/Dialog.js', css: 'dialog/src/dialog.css.js' },
  { name: 'divider', tag: 'sp-divider', pkg: '@spectrum-web-components', source: 'divider/src/Divider.js', css: 'divider/src/divider.css.js' },
  { name: 'dropzone', tag: 'sp-dropzone', pkg: '@spectrum-web-components', source: 'dropzone/src/Dropzone.js', css: 'dropzone/src/dropzone.css.js' },
  { name: 'field-group', tag: 'sp-field-group', pkg: '@spectrum-web-components', source: 'field-group/src/FieldGroup.js', css: 'field-group/src/field-group.css.js' },
  { name: 'field-label', tag: 'sp-field-label', pkg: '@spectrum-web-components', source: 'field-label/src/FieldLabel.js', css: 'field-label/src/field-label.css.js' },
  { name: 'help-text', tag: 'sp-help-text', pkg: '@spectrum-web-components', source: 'help-text/src/HelpText.js', css: 'help-text/src/help-text.css.js' },
  { name: 'icon', tag: 'sp-icon', pkg: '@spectrum-web-components', source: 'icon/src/Icon.js', css: 'icon/src/icon.css.js' },
  { name: 'link', tag: 'sp-link', pkg: '@spectrum-web-components', source: 'link/src/Link.js', css: 'link/src/link.css.js' },
  { name: 'menu', tag: 'sp-menu', pkg: '@spectrum-web-components', source: 'menu/src/Menu.js', css: 'menu/src/menu.css.js' },
  { name: 'menu-divider', tag: 'sp-menu-divider', pkg: '@spectrum-web-components', source: 'menu/src/MenuDivider.js', css: 'menu/src/menu-divider.css.js' },
  { name: 'menu-group', tag: 'sp-menu-group', pkg: '@spectrum-web-components', source: 'menu/src/MenuGroup.js', css: 'menu/src/menu-group.css.js' },
  { name: 'menu-item', tag: 'sp-menu-item', pkg: '@spectrum-web-components', source: 'menu/src/MenuItem.js', css: 'menu/src/menu-item.css.js' },
  { name: 'meter', tag: 'sp-meter', pkg: '@spectrum-web-components', source: 'meter/src/Meter.js', css: 'meter/src/meter.css.js' },
  { name: 'number-field', tag: 'sp-number-field', pkg: '@spectrum-web-components', source: 'number-field/src/NumberField.js', css: 'number-field/src/number-field.css.js' },
  { name: 'overlay', tag: 'sp-overlay', pkg: '@spectrum-web-components', source: 'overlay/src/Overlay.js', css: 'overlay/src/overlay.css.js' },
  { name: 'picker', tag: 'sp-picker', pkg: '@spectrum-web-components', source: 'picker/src/Picker.js', css: 'picker/src/picker.css.js' },
  { name: 'picker-button', tag: 'sp-picker-button', pkg: '@spectrum-web-components', source: 'picker-button/src/PickerButton.js', css: 'picker-button/src/picker-button.css.js' },
  { name: 'popover', tag: 'sp-popover', pkg: '@spectrum-web-components', source: 'popover/src/Popover.js', css: 'popover/src/popover.css.js' },
  { name: 'progress-bar', tag: 'sp-progress-bar', pkg: '@spectrum-web-components', source: 'progress-bar/src/ProgressBar.js', css: 'progress-bar/src/progress-bar.css.js' },
  { name: 'progress-circle', tag: 'sp-progress-circle', pkg: '@spectrum-web-components', source: 'progress-circle/src/ProgressCircle.js', css: 'progress-circle/src/progress-circle.css.js' },
  { name: 'radio', tag: 'sp-radio', pkg: '@spectrum-web-components', source: 'radio/src/Radio.js', css: 'radio/src/radio.css.js' },
  { name: 'radio-group', tag: 'sp-radio-group', pkg: '@spectrum-web-components', source: 'radio/src/RadioGroup.js', css: 'radio/src/radio.css.js' },
  { name: 'search', tag: 'sp-search', pkg: '@spectrum-web-components', source: 'search/src/Search.js', css: 'search/src/search.css.js' },
  { name: 'sidenav', tag: 'sp-sidenav', pkg: '@spectrum-web-components', source: 'sidenav/src/Sidenav.js', css: 'sidenav/src/sidenav.css.js' },
  { name: 'slider', tag: 'sp-slider', pkg: '@spectrum-web-components', source: 'slider/src/Slider.js', css: 'slider/src/slider.css.js' },
  { name: 'status-light', tag: 'sp-status-light', pkg: '@spectrum-web-components', source: 'status-light/src/StatusLight.js', css: 'status-light/src/status-light.css.js' },
  { name: 'switch', tag: 'sp-switch', pkg: '@spectrum-web-components', source: 'switch/src/Switch.js', css: 'switch/src/switch.css.js' },
];

// 51 Web Awesome Components
export const WEBAWESOME_COMPONENTS: ComponentDescriptor[] = [
  { name: 'accordion', tag: 'wa-accordion', pkg: '@awesome.me/webawesome', source: 'dist/components/accordion/accordion.js', css: 'dist/components/accordion/accordion.styles.js' },
  {
    name: 'accordion-item',
    tag: 'wa-accordion-item',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/accordion-item/accordion-item.js',
    css: 'dist/components/accordion-item/accordion-item.styles.js',
  },
  {
    name: 'animated-image',
    tag: 'wa-animated-image',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/animated-image/animated-image.js',
    css: 'dist/components/animated-image/animated-image.styles.js',
  },
  { name: 'animation', tag: 'wa-animation', pkg: '@awesome.me/webawesome', source: 'dist/components/animation/animation.js', css: 'dist/components/animation/animation.styles.js' },
  { name: 'avatar', tag: 'wa-avatar', pkg: '@awesome.me/webawesome', source: 'dist/components/avatar/avatar.js', css: 'dist/components/avatar/avatar.styles.js' },
  { name: 'badge', tag: 'wa-badge', pkg: '@awesome.me/webawesome', source: 'dist/components/badge/badge.js', css: 'dist/components/badge/badge.styles.js' },
  { name: 'breadcrumb', tag: 'wa-breadcrumb', pkg: '@awesome.me/webawesome', source: 'dist/components/breadcrumb/breadcrumb.js', css: 'dist/components/breadcrumb/breadcrumb.styles.js' },
  {
    name: 'breadcrumb-item',
    tag: 'wa-breadcrumb-item',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/breadcrumb-item/breadcrumb-item.js',
    css: 'dist/components/breadcrumb-item/breadcrumb-item.styles.js',
  },
  { name: 'button', tag: 'wa-button', pkg: '@awesome.me/webawesome', source: 'dist/components/button/button.js', css: 'dist/components/button/button.styles.js' },
  { name: 'button-group', tag: 'wa-button-group', pkg: '@awesome.me/webawesome', source: 'dist/components/button-group/button-group.js', css: 'dist/components/button-group/button-group.styles.js' },
  { name: 'callout', tag: 'wa-callout', pkg: '@awesome.me/webawesome', source: 'dist/components/callout/callout.js', css: 'dist/components/callout/callout.styles.js' },
  { name: 'card', tag: 'wa-card', pkg: '@awesome.me/webawesome', source: 'dist/components/card/card.js', css: 'dist/components/card/card.styles.js' },
  { name: 'carousel', tag: 'wa-carousel', pkg: '@awesome.me/webawesome', source: 'dist/components/carousel/carousel.js', css: 'dist/components/carousel/carousel.styles.js' },
  {
    name: 'carousel-item',
    tag: 'wa-carousel-item',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/carousel-item/carousel-item.js',
    css: 'dist/components/carousel-item/carousel-item.styles.js',
  },
  { name: 'checkbox', tag: 'wa-checkbox', pkg: '@awesome.me/webawesome', source: 'dist/components/checkbox/checkbox.js', css: 'dist/components/checkbox/checkbox.styles.js' },
  {
    name: 'checkbox-group',
    tag: 'wa-checkbox-group',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/checkbox-group/checkbox-group.js',
    css: 'dist/components/checkbox-group/checkbox-group.styles.js',
  },
  { name: 'color-picker', tag: 'wa-color-picker', pkg: '@awesome.me/webawesome', source: 'dist/components/color-picker/color-picker.js', css: 'dist/components/color-picker/color-picker.styles.js' },
  { name: 'comparison', tag: 'wa-comparison', pkg: '@awesome.me/webawesome', source: 'dist/components/comparison/comparison.js', css: 'dist/components/comparison/comparison.styles.js' },
  { name: 'copy-button', tag: 'wa-copy-button', pkg: '@awesome.me/webawesome', source: 'dist/components/copy-button/copy-button.js', css: 'dist/components/copy-button/copy-button.styles.js' },
  { name: 'details', tag: 'wa-details', pkg: '@awesome.me/webawesome', source: 'dist/components/details/details.js', css: 'dist/components/details/details.styles.js' },
  { name: 'dialog', tag: 'wa-dialog', pkg: '@awesome.me/webawesome', source: 'dist/components/dialog/dialog.js', css: 'dist/components/dialog/dialog.styles.js' },
  { name: 'divider', tag: 'wa-divider', pkg: '@awesome.me/webawesome', source: 'dist/components/divider/divider.js', css: 'dist/components/divider/divider.styles.js' },
  { name: 'drawer', tag: 'wa-drawer', pkg: '@awesome.me/webawesome', source: 'dist/components/drawer/drawer.js', css: 'dist/components/drawer/drawer.styles.js' },
  { name: 'dropdown', tag: 'wa-dropdown', pkg: '@awesome.me/webawesome', source: 'dist/components/dropdown/dropdown.js', css: 'dist/components/dropdown/dropdown.styles.js' },
  {
    name: 'dropdown-item',
    tag: 'wa-dropdown-item',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/dropdown-item/dropdown-item.js',
    css: 'dist/components/dropdown-item/dropdown-item.styles.js',
  },
  { name: 'format-bytes', tag: 'wa-format-bytes', pkg: '@awesome.me/webawesome', source: 'dist/components/format-bytes/format-bytes.js', css: 'dist/components/format-bytes/format-bytes.styles.js' },
  { name: 'format-date', tag: 'wa-format-date', pkg: '@awesome.me/webawesome', source: 'dist/components/format-date/format-date.js', css: 'dist/components/format-date/format-date.styles.js' },
  {
    name: 'format-number',
    tag: 'wa-format-number',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/format-number/format-number.js',
    css: 'dist/components/format-number/format-number.styles.js',
  },
  { name: 'icon', tag: 'wa-icon', pkg: '@awesome.me/webawesome', source: 'dist/components/icon/icon.js', css: 'dist/components/icon/icon.styles.js' },
  { name: 'include', tag: 'wa-include', pkg: '@awesome.me/webawesome', source: 'dist/components/include/include.js', css: 'dist/components/include/include.styles.js' },
  { name: 'input', tag: 'wa-input', pkg: '@awesome.me/webawesome', source: 'dist/components/input/input.js', css: 'dist/components/input/input.styles.js' },
  {
    name: 'intersection-observer',
    tag: 'wa-intersection-observer',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/intersection-observer/intersection-observer.js',
    css: 'dist/components/intersection-observer/intersection-observer.styles.js',
  },
  { name: 'known-date', tag: 'wa-known-date', pkg: '@awesome.me/webawesome', source: 'dist/components/known-date/known-date.js', css: 'dist/components/known-date/known-date.styles.js' },
  { name: 'markdown', tag: 'wa-markdown', pkg: '@awesome.me/webawesome', source: 'dist/components/markdown/markdown.js', css: 'dist/components/markdown/markdown.styles.js' },
  {
    name: 'mutation-observer',
    tag: 'wa-mutation-observer',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/mutation-observer/mutation-observer.js',
    css: 'dist/components/mutation-observer/mutation-observer.styles.js',
  },
  { name: 'number-input', tag: 'wa-number-input', pkg: '@awesome.me/webawesome', source: 'dist/components/number-input/number-input.js', css: 'dist/components/number-input/number-input.styles.js' },
  { name: 'option', tag: 'wa-option', pkg: '@awesome.me/webawesome', source: 'dist/components/option/option.js', css: 'dist/components/option/option.styles.js' },
  { name: 'otp-input', tag: 'wa-otp-input', pkg: '@awesome.me/webawesome', source: 'dist/components/otp-input/otp-input.js', css: 'dist/components/otp-input/otp-input.styles.js' },
  { name: 'page', tag: 'wa-page', pkg: '@awesome.me/webawesome', source: 'dist/components/page/page.js', css: 'dist/components/page/page.styles.js' },
  { name: 'pagination', tag: 'wa-pagination', pkg: '@awesome.me/webawesome', source: 'dist/components/pagination/pagination.js', css: 'dist/components/pagination/pagination.styles.js' },
  { name: 'popover', tag: 'wa-popover', pkg: '@awesome.me/webawesome', source: 'dist/components/popover/popover.js', css: 'dist/components/popover/popover.styles.js' },
  { name: 'popup', tag: 'wa-popup', pkg: '@awesome.me/webawesome', source: 'dist/components/popup/popup.js', css: 'dist/components/popup/popup.styles.js' },
  { name: 'progress-bar', tag: 'wa-progress-bar', pkg: '@awesome.me/webawesome', source: 'dist/components/progress-bar/progress-bar.js', css: 'dist/components/progress-bar/progress-bar.styles.js' },
  {
    name: 'progress-ring',
    tag: 'wa-progress-ring',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/progress-ring/progress-ring.js',
    css: 'dist/components/progress-ring/progress-ring.styles.js',
  },
  { name: 'qr-code', tag: 'wa-qr-code', pkg: '@awesome.me/webawesome', source: 'dist/components/qr-code/qr-code.js', css: 'dist/components/qr-code/qr-code.styles.js' },
  { name: 'radio', tag: 'wa-radio', pkg: '@awesome.me/webawesome', source: 'dist/components/radio/radio.js', css: 'dist/components/radio/radio.styles.js' },
  { name: 'radio-group', tag: 'wa-radio-group', pkg: '@awesome.me/webawesome', source: 'dist/components/radio-group/radio-group.js', css: 'dist/components/radio-group/radio-group.styles.js' },
  {
    name: 'random-content',
    tag: 'wa-random-content',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/random-content/random-content.js',
    css: 'dist/components/random-content/random-content.styles.js',
  },
  { name: 'rating', tag: 'wa-rating', pkg: '@awesome.me/webawesome', source: 'dist/components/rating/rating.js', css: 'dist/components/rating/rating.styles.js' },
  {
    name: 'relative-time',
    tag: 'wa-relative-time',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/relative-time/relative-time.js',
    css: 'dist/components/relative-time/relative-time.styles.js',
  },
  {
    name: 'resize-observer',
    tag: 'wa-resize-observer',
    pkg: '@awesome.me/webawesome',
    source: 'dist/components/resize-observer/resize-observer.js',
    css: 'dist/components/resize-observer/resize-observer.styles.js',
  },
];

// 51 Google Material Web Components
export const MATERIAL_COMPONENTS: ComponentDescriptor[] = [
  { name: 'elevated-button', tag: 'md-elevated-button', pkg: '@material/web', source: 'button/elevated-button.js', css: 'button/internal/elevated-styles.cssresult.js' },
  { name: 'filled-button', tag: 'md-filled-button', pkg: '@material/web', source: 'button/filled-button.js', css: 'button/internal/filled-styles.cssresult.js' },
  { name: 'filled-tonal-button', tag: 'md-filled-tonal-button', pkg: '@material/web', source: 'button/filled-tonal-button.js', css: 'button/internal/filled-tonal-styles.cssresult.js' },
  { name: 'outlined-button', tag: 'md-outlined-button', pkg: '@material/web', source: 'button/outlined-button.js', css: 'button/internal/outlined-styles.cssresult.js' },
  { name: 'text-button', tag: 'md-text-button', pkg: '@material/web', source: 'button/text-button.js', css: 'button/internal/text-styles.cssresult.js' },
  { name: 'button-internal', tag: 'md-button-base', pkg: '@material/web', source: 'button/internal/button.js', css: 'button/internal/shared-styles.cssresult.js' },
  { name: 'checkbox', tag: 'md-checkbox', pkg: '@material/web', source: 'checkbox/checkbox.js', css: 'checkbox/internal/checkbox-styles.cssresult.js' },
  { name: 'assist-chip', tag: 'md-assist-chip', pkg: '@material/web', source: 'chips/assist-chip.js', css: 'chips/internal/assist-chip-styles.cssresult.js' },
  { name: 'chip-set', tag: 'md-chip-set', pkg: '@material/web', source: 'chips/chip-set.js', css: 'chips/internal/chip-set-styles.cssresult.js' },
  { name: 'filter-chip', tag: 'md-filter-chip', pkg: '@material/web', source: 'chips/filter-chip.js', css: 'chips/internal/filter-chip-styles.cssresult.js' },
  { name: 'input-chip', tag: 'md-input-chip', pkg: '@material/web', source: 'chips/input-chip.js', css: 'chips/internal/input-chip-styles.cssresult.js' },
  { name: 'suggestion-chip', tag: 'md-suggestion-chip', pkg: '@material/web', source: 'chips/suggestion-chip.js', css: 'chips/internal/suggestion-chip-styles.cssresult.js' },
  { name: 'dialog', tag: 'md-dialog', pkg: '@material/web', source: 'dialog/dialog.js', css: 'dialog/internal/dialog-styles.cssresult.js' },
  { name: 'divider', tag: 'md-divider', pkg: '@material/web', source: 'divider/divider.js', css: 'divider/internal/divider-styles.cssresult.js' },
  { name: 'elevation', tag: 'md-elevation', pkg: '@material/web', source: 'elevation/elevation.js', css: 'elevation/internal/elevation-styles.cssresult.js' },
  { name: 'fab', tag: 'md-fab', pkg: '@material/web', source: 'fab/fab.js', css: 'fab/internal/fab-styles.cssresult.js' },
  { name: 'branded-fab', tag: 'md-branded-fab', pkg: '@material/web', source: 'fab/branded-fab.js', css: 'fab/internal/fab-branded-styles.cssresult.js' },
  { name: 'filled-field', tag: 'md-filled-field', pkg: '@material/web', source: 'field/filled-field.js', css: 'field/internal/filled-field-styles.cssresult.js' },
  { name: 'outlined-field', tag: 'md-outlined-field', pkg: '@material/web', source: 'field/outlined-field.js', css: 'field/internal/outlined-field-styles.cssresult.js' },
  { name: 'focus-ring', tag: 'md-focus-ring', pkg: '@material/web', source: 'focus/md-focus-ring.js', css: 'focus/internal/focus-ring-styles.cssresult.js' },
  { name: 'icon', tag: 'md-icon', pkg: '@material/web', source: 'icon/icon.js', css: 'icon/internal/icon-styles.cssresult.js' },
  { name: 'icon-button', tag: 'md-icon-button', pkg: '@material/web', source: 'iconbutton/icon-button.js', css: 'iconbutton/internal/standard-icon-button-styles.cssresult.js' },
  { name: 'filled-icon-button', tag: 'md-filled-icon-button', pkg: '@material/web', source: 'iconbutton/filled-icon-button.js', css: 'iconbutton/internal/filled-icon-button-styles.cssresult.js' },
  {
    name: 'filled-tonal-icon-button',
    tag: 'md-filled-tonal-icon-button',
    pkg: '@material/web',
    source: 'iconbutton/filled-tonal-icon-button.js',
    css: 'iconbutton/internal/filled-tonal-icon-button-styles.cssresult.js',
  },
  {
    name: 'outlined-icon-button',
    tag: 'md-outlined-icon-button',
    pkg: '@material/web',
    source: 'iconbutton/outlined-icon-button.js',
    css: 'iconbutton/internal/outlined-icon-button-styles.cssresult.js',
  },
  { name: 'list', tag: 'md-list', pkg: '@material/web', source: 'list/list.js', css: 'list/internal/list-styles.cssresult.js' },
  { name: 'list-item', tag: 'md-list-item', pkg: '@material/web', source: 'list/list-item.js', css: 'list/internal/list-item-styles.cssresult.js' },
  { name: 'menu', tag: 'md-menu', pkg: '@material/web', source: 'menu/menu.js', css: 'menu/internal/menu-styles.cssresult.js' },
  { name: 'menu-item', tag: 'md-menu-item', pkg: '@material/web', source: 'menu/menu-item.js', css: 'menu/internal/menu-item-styles.cssresult.js' },
  { name: 'sub-menu', tag: 'md-sub-menu', pkg: '@material/web', source: 'menu/sub-menu.js', css: 'menu/internal/menu-styles.cssresult.js' },
  { name: 'circular-progress', tag: 'md-circular-progress', pkg: '@material/web', source: 'progress/circular-progress.js', css: 'progress/internal/circular-progress-styles.cssresult.js' },
  { name: 'linear-progress', tag: 'md-linear-progress', pkg: '@material/web', source: 'progress/linear-progress.js', css: 'progress/internal/linear-progress-styles.cssresult.js' },
  { name: 'radio', tag: 'md-radio', pkg: '@material/web', source: 'radio/radio.js', css: 'radio/internal/radio-styles.cssresult.js' },
  { name: 'ripple', tag: 'md-ripple', pkg: '@material/web', source: 'ripple/ripple.js', css: 'ripple/internal/ripple-styles.cssresult.js' },
  { name: 'filled-select', tag: 'md-filled-select', pkg: '@material/web', source: 'select/filled-select.js', css: 'select/internal/filled-select-styles.cssresult.js' },
  { name: 'outlined-select', tag: 'md-outlined-select', pkg: '@material/web', source: 'select/outlined-select.js', css: 'select/internal/outlined-select-styles.cssresult.js' },
  { name: 'select-option', tag: 'md-select-option', pkg: '@material/web', source: 'select/select-option.js', css: 'select/internal/select-option-styles.cssresult.js' },
  { name: 'slider', tag: 'md-slider', pkg: '@material/web', source: 'slider/slider.js', css: 'slider/internal/slider-styles.cssresult.js' },
  { name: 'switch', tag: 'md-switch', pkg: '@material/web', source: 'switch/switch.js', css: 'switch/internal/switch-styles.cssresult.js' },
  { name: 'tabs', tag: 'md-tabs', pkg: '@material/web', source: 'tabs/tabs.js', css: 'tabs/internal/tabs-styles.cssresult.js' },
  { name: 'primary-tab', tag: 'md-primary-tab', pkg: '@material/web', source: 'tabs/primary-tab.js', css: 'tabs/internal/primary-tab-styles.cssresult.js' },
  { name: 'secondary-tab', tag: 'md-secondary-tab', pkg: '@material/web', source: 'tabs/secondary-tab.js', css: 'tabs/internal/secondary-tab-styles.cssresult.js' },
  { name: 'filled-text-field', tag: 'md-filled-text-field', pkg: '@material/web', source: 'textfield/filled-text-field.js', css: 'textfield/internal/filled-text-field-styles.cssresult.js' },
  { name: 'outlined-text-field', tag: 'md-outlined-text-field', pkg: '@material/web', source: 'textfield/outlined-text-field.js', css: 'textfield/internal/outlined-text-field-styles.cssresult.js' },
  { name: 'badge', tag: 'md-badge', pkg: '@material/web', source: 'labs/badge/badge.js', css: 'labs/badge/internal/badge-styles.cssresult.js' },
  { name: 'navigation-bar', tag: 'md-navigation-bar', pkg: '@material/web', source: 'labs/navigationbar/navigation-bar.js', css: 'labs/navigationbar/internal/navigation-bar-styles.cssresult.js' },
  {
    name: 'navigation-drawer',
    tag: 'md-navigation-drawer',
    pkg: '@material/web',
    source: 'labs/navigationdrawer/navigation-drawer.js',
    css: 'labs/navigationdrawer/internal/navigation-drawer-styles.cssresult.js',
  },
  { name: 'navigation-tab', tag: 'md-navigation-tab', pkg: '@material/web', source: 'labs/navigationtab/navigation-tab.js', css: 'labs/navigationtab/internal/navigation-tab-styles.cssresult.js' },
  {
    name: 'segmented-button',
    tag: 'md-segmented-button',
    pkg: '@material/web',
    source: 'labs/segmentedbutton/outlined-segmented-button.js',
    css: 'labs/segmentedbutton/internal/outlined-styles.cssresult.js',
  },
  {
    name: 'segmented-button-set',
    tag: 'md-segmented-button-set',
    pkg: '@material/web',
    source: 'labs/segmentedbuttonset/outlined-segmented-button-set.js',
    css: 'labs/segmentedbuttonset/internal/outlined-styles.cssresult.js',
  },
  { name: 'card', tag: 'md-elevated-card', pkg: '@material/web', source: 'labs/card/elevated-card.js', css: 'labs/card/internal/elevated-styles.cssresult.js' },
];

// 51 Cisco Momentum Design Components
export const MOMENTUM_COMPONENTS: ComponentDescriptor[] = [
  { name: 'accordion', tag: 'mdc-accordion', pkg: '@momentum-design/components', source: 'dist/components/accordion/accordion.component.js', css: 'dist/components/accordion/accordion.styles.js' },
  {
    name: 'accordionbutton',
    tag: 'mdc-accordionbutton',
    pkg: '@momentum-design/components',
    source: 'dist/components/accordionbutton/accordionbutton.component.js',
    css: 'dist/components/accordionbutton/accordionbutton.styles.js',
  },
  {
    name: 'accordiongroup',
    tag: 'mdc-accordiongroup',
    pkg: '@momentum-design/components',
    source: 'dist/components/accordiongroup/accordiongroup.component.js',
    css: 'dist/components/accordiongroup/accordiongroup.styles.js',
  },
  { name: 'alertchip', tag: 'mdc-alertchip', pkg: '@momentum-design/components', source: 'dist/components/alertchip/alertchip.component.js', css: 'dist/components/alertchip/alertchip.styles.js' },
  { name: 'animation', tag: 'mdc-animation', pkg: '@momentum-design/components', source: 'dist/components/animation/animation.component.js', css: 'dist/components/animation/animation.styles.js' },
  { name: 'avatar', tag: 'mdc-avatar', pkg: '@momentum-design/components', source: 'dist/components/avatar/avatar.component.js', css: 'dist/components/avatar/avatar.styles.js' },
  {
    name: 'avatarbutton',
    tag: 'mdc-avatarbutton',
    pkg: '@momentum-design/components',
    source: 'dist/components/avatarbutton/avatarbutton.component.js',
    css: 'dist/components/avatarbutton/avatarbutton.styles.js',
  },
  { name: 'badge', tag: 'mdc-badge', pkg: '@momentum-design/components', source: 'dist/components/badge/badge.component.js', css: 'dist/components/badge/badge.styles.js' },
  { name: 'banner', tag: 'mdc-banner', pkg: '@momentum-design/components', source: 'dist/components/banner/banner.component.js', css: 'dist/components/banner/banner.styles.js' },
  { name: 'bullet', tag: 'mdc-bullet', pkg: '@momentum-design/components', source: 'dist/components/bullet/bullet.component.js', css: 'dist/components/bullet/bullet.styles.js' },
  { name: 'button', tag: 'mdc-button', pkg: '@momentum-design/components', source: 'dist/components/button/button.component.js', css: 'dist/components/button/button.styles.js' },
  {
    name: 'buttongroup',
    tag: 'mdc-buttongroup',
    pkg: '@momentum-design/components',
    source: 'dist/components/buttongroup/buttongroup.component.js',
    css: 'dist/components/buttongroup/buttongroup.styles.js',
  },
  {
    name: 'buttonlink',
    tag: 'mdc-buttonlink',
    pkg: '@momentum-design/components',
    source: 'dist/components/buttonlink/buttonlink.component.js',
    css: 'dist/components/buttonlink/buttonlink.styles.js',
  },
  {
    name: 'buttonsimple',
    tag: 'mdc-buttonsimple',
    pkg: '@momentum-design/components',
    source: 'dist/components/buttonsimple/buttonsimple.component.js',
    css: 'dist/components/buttonsimple/buttonsimple.styles.js',
  },
  { name: 'calendar', tag: 'mdc-calendar', pkg: '@momentum-design/components', source: 'dist/components/calendar/calendar.component.js', css: 'dist/components/calendar/calendar.styles.js' },
  { name: 'card', tag: 'mdc-card', pkg: '@momentum-design/components', source: 'dist/components/card/card.component.js', css: 'dist/components/card/card.styles.js' },
  {
    name: 'cardbutton',
    tag: 'mdc-cardbutton',
    pkg: '@momentum-design/components',
    source: 'dist/components/cardbutton/cardbutton.component.js',
    css: 'dist/components/cardbutton/cardbutton.styles.js',
  },
  {
    name: 'cardcheckbox',
    tag: 'mdc-cardcheckbox',
    pkg: '@momentum-design/components',
    source: 'dist/components/cardcheckbox/cardcheckbox.component.js',
    css: 'dist/components/cardcheckbox/cardcheckbox.styles.js',
  },
  { name: 'cardradio', tag: 'mdc-cardradio', pkg: '@momentum-design/components', source: 'dist/components/cardradio/cardradio.component.js', css: 'dist/components/cardradio/cardradio.styles.js' },
  { name: 'checkbox', tag: 'mdc-checkbox', pkg: '@momentum-design/components', source: 'dist/components/checkbox/checkbox.component.js', css: 'dist/components/checkbox/checkbox.styles.js' },
  {
    name: 'checkboxtree',
    tag: 'mdc-checkboxtree',
    pkg: '@momentum-design/components',
    source: 'dist/components/checkboxtree/checkboxtree.component.js',
    css: 'dist/components/checkboxtree/checkboxtree.styles.js',
  },
  { name: 'chip', tag: 'mdc-chip', pkg: '@momentum-design/components', source: 'dist/components/chip/chip.component.js', css: 'dist/components/chip/chip.styles.js' },
  { name: 'coachmark', tag: 'mdc-coachmark', pkg: '@momentum-design/components', source: 'dist/components/coachmark/coachmark.component.js', css: 'dist/components/coachmark/coachmark.styles.js' },
  { name: 'combobox', tag: 'mdc-combobox', pkg: '@momentum-design/components', source: 'dist/components/combobox/combobox.component.js', css: 'dist/components/combobox/combobox.styles.js' },
  {
    name: 'datepicker',
    tag: 'mdc-datepicker',
    pkg: '@momentum-design/components',
    source: 'dist/components/datepicker/datepicker.component.js',
    css: 'dist/components/datepicker/datepicker.styles.js',
  },
  { name: 'dialog', tag: 'mdc-dialog', pkg: '@momentum-design/components', source: 'dist/components/dialog/dialog.component.js', css: 'dist/components/dialog/dialog.styles.js' },
  { name: 'divider', tag: 'mdc-divider', pkg: '@momentum-design/components', source: 'dist/components/divider/divider.component.js', css: 'dist/components/divider/divider.styles.js' },
  {
    name: 'filterchip',
    tag: 'mdc-filterchip',
    pkg: '@momentum-design/components',
    source: 'dist/components/filterchip/filterchip.component.js',
    css: 'dist/components/filterchip/filterchip.styles.js',
  },
  { name: 'icon', tag: 'mdc-icon', pkg: '@momentum-design/components', source: 'dist/components/icon/icon.component.js', css: 'dist/components/icon/icon.styles.js' },
  { name: 'input', tag: 'mdc-input', pkg: '@momentum-design/components', source: 'dist/components/input/input.component.js', css: 'dist/components/input/input.styles.js' },
  { name: 'inputchip', tag: 'mdc-inputchip', pkg: '@momentum-design/components', source: 'dist/components/inputchip/inputchip.component.js', css: 'dist/components/inputchip/inputchip.styles.js' },
  { name: 'link', tag: 'mdc-link', pkg: '@momentum-design/components', source: 'dist/components/link/link.component.js', css: 'dist/components/link/link.styles.js' },
  {
    name: 'linkbutton',
    tag: 'mdc-linkbutton',
    pkg: '@momentum-design/components',
    source: 'dist/components/linkbutton/linkbutton.component.js',
    css: 'dist/components/linkbutton/linkbutton.styles.js',
  },
  { name: 'list', tag: 'mdc-list', pkg: '@momentum-design/components', source: 'dist/components/list/list.component.js', css: 'dist/components/list/list.styles.js' },
  { name: 'listbox', tag: 'mdc-listbox', pkg: '@momentum-design/components', source: 'dist/components/listbox/listbox.component.js', css: 'dist/components/listbox/listbox.styles.js' },
  {
    name: 'listheader',
    tag: 'mdc-listheader',
    pkg: '@momentum-design/components',
    source: 'dist/components/listheader/listheader.component.js',
    css: 'dist/components/listheader/listheader.styles.js',
  },
  { name: 'listitem', tag: 'mdc-listitem', pkg: '@momentum-design/components', source: 'dist/components/listitem/listitem.component.js', css: 'dist/components/listitem/listitem.styles.js' },
  { name: 'menubar', tag: 'mdc-menubar', pkg: '@momentum-design/components', source: 'dist/components/menubar/menubar.component.js', css: 'dist/components/menubar/menubar.styles.js' },
  { name: 'menuitem', tag: 'mdc-menuitem', pkg: '@momentum-design/components', source: 'dist/components/menuitem/menuitem.component.js', css: 'dist/components/menuitem/menuitem.styles.js' },
  { name: 'password', tag: 'mdc-password', pkg: '@momentum-design/components', source: 'dist/components/password/password.component.js', css: 'dist/components/password/password.styles.js' },
  { name: 'popover', tag: 'mdc-popover', pkg: '@momentum-design/components', source: 'dist/components/popover/popover.component.js', css: 'dist/components/popover/popover.styles.js' },
  { name: 'presence', tag: 'mdc-presence', pkg: '@momentum-design/components', source: 'dist/components/presence/presence.component.js', css: 'dist/components/presence/presence.styles.js' },
  {
    name: 'progressbar',
    tag: 'mdc-progressbar',
    pkg: '@momentum-design/components',
    source: 'dist/components/progressbar/progressbar.component.js',
    css: 'dist/components/progressbar/progressbar.styles.js',
  },
  {
    name: 'progressspinner',
    tag: 'mdc-progressspinner',
    pkg: '@momentum-design/components',
    source: 'dist/components/progressspinner/progressspinner.component.js',
    css: 'dist/components/progressspinner/progressspinner.styles.js',
  },
  { name: 'radio', tag: 'mdc-radio', pkg: '@momentum-design/components', source: 'dist/components/radio/radio.component.js', css: 'dist/components/radio/radio.styles.js' },
  {
    name: 'radiogroup',
    tag: 'mdc-radiogroup',
    pkg: '@momentum-design/components',
    source: 'dist/components/radiogroup/radiogroup.component.js',
    css: 'dist/components/radiogroup/radiogroup.styles.js',
  },
  {
    name: 'searchfield',
    tag: 'mdc-searchfield',
    pkg: '@momentum-design/components',
    source: 'dist/components/searchfield/searchfield.component.js',
    css: 'dist/components/searchfield/searchfield.styles.js',
  },
  { name: 'select', tag: 'mdc-select', pkg: '@momentum-design/components', source: 'dist/components/select/select.component.js', css: 'dist/components/select/select.styles.js' },
  { name: 'skeleton', tag: 'mdc-skeleton', pkg: '@momentum-design/components', source: 'dist/components/skeleton/skeleton.component.js', css: 'dist/components/skeleton/skeleton.styles.js' },
  { name: 'slider', tag: 'mdc-slider', pkg: '@momentum-design/components', source: 'dist/components/slider/slider.component.js', css: 'dist/components/slider/slider.styles.js' },
  { name: 'spinner', tag: 'mdc-spinner', pkg: '@momentum-design/components', source: 'dist/components/spinner/spinner.component.js', css: 'dist/components/spinner/spinner.styles.js' },
];
