use crate::models::{ClusterGroup, FusedSheetInfo};
use std::collections::BTreeMap;

pub fn generate_fused_sheet(cluster: &ClusterGroup) -> FusedSheetInfo {
    let mut grouped: BTreeMap<(Option<String>, String), Vec<String>> = BTreeMap::new();
    for rule in &cluster.rules {
        let key = (rule.at_rule.clone(), rule.selector.clone());
        let decls = grouped.entry(key).or_default();
        for d in &rule.declarations {
            if !decls.contains(d) {
                decls.push(d.clone());
            }
        }
    }

    let mut css_rules = String::new();
    for ((at_rule, selector), decls) in grouped {
        let body = decls.join(";");
        css_rules.push_str("  ");
        if let Some(at) = at_rule {
            css_rules.push_str(&format!("{} {{\n    {} {{{}}}\n  }}", at, selector, body));
        } else {
            css_rules.push_str(&format!("{} {{{}}}", selector, body));
        }
        css_rules.push('\n');
    }

    let code = format!(
        "// Auto-generated by @lit-core/css-fuse. Do not edit.\n\
import {{ css }} from 'lit';\n\n\
export const {} = css`\n\
{}`;\n",
        cluster.id, css_rules
    );

    FusedSheetInfo {
        id: cluster.id.clone(),
        file_name: cluster.fused_sheet_name.clone(),
        code,
        rules_count: cluster.rules.len() as u32,
        shared_by: cluster.shared_by_files.clone(),
    }
}
