use crate::models::{ClusterGroup, FusedSheetInfo};

pub fn generate_fused_sheet(cluster: &ClusterGroup) -> FusedSheetInfo {
    let mut css_rules = String::new();
    for rule in &cluster.rules {
        css_rules.push_str("  ");
        css_rules.push_str(&rule.full_canonical_css);
        css_rules.push('\n');
    }

    let code = format!(
        "// Auto-generated by @lit-core/css-fuse. Do not edit.\n\
import {{ css }} from 'lit';\n\n\
export const {} = css`\n\
{}`;\n",
        cluster.id, css_rules
    );

    FusedSheetInfo {
        id: cluster.id.clone(),
        file_name: cluster.fused_sheet_name.clone(),
        code,
        rules_count: cluster.rules.len() as u32,
        shared_by: cluster.shared_by_files.clone(),
    }
}
