export type {
  CssFuseOptions,
  CssMinifierOptions,
  ElemProxyOptions,
  HtmlAotOptions,
  HtmlFuseOptions,
  HtmlMinifierOptions,
  LitCorePluginOptions,
  LitCssFuseOptions,
  LitCssMinifierOptions,
  LitElemProxyOptions,
  LitHtmlAotOptions,
  LitHtmlFuseOptions,
  LitHtmlMinifierOptions,
  LitPluginOptions,
  LitPropsLowerOptions,
  PropsLowerOptions,
} from './options.js';
export {
  cssFuse,
  cssMinifier,
  elemProxy,
  htmlAot,
  htmlFuse,
  htmlMinifier,
  lit,
  lit as default,
  litCore,
  litCssFuse,
  litCssMinifier,
  litElemProxy,
  litHtmlAot,
  litHtmlFuse,
  litHtmlMinifier,
  litPropsLower,
  propsLower,
} from './plugin.js';
