/// <reference types="node" />

export {
  default as litWebpackLoader,
  getPluginState,
  registerPluginState,
  unregisterPluginState,
} from './loader.js';
export type {
  CssFuseOptions,
  CssMinifierOptions,
  DirectivesOptions,
  DirtyMaskOptions,
  DomPathsOptions,
  ElemProxyOptions,
  EventHoistOptions,
  HtmlAotOptions,
  HtmlFuseOptions,
  HtmlMinifierOptions,
  LitCorePluginOptions,
  LitCssFuseOptions,
  LitCssMinifierOptions,
  LitDirectivesOptions,
  LitDirtyMaskOptions,
  LitDomPathsOptions,
  LitElemProxyOptions,
  LitEventHoistOptions,
  LitHtmlAotOptions,
  LitHtmlFuseOptions,
  LitHtmlMinifierOptions,
  LitMemoizeOptions,
  LitPluginOptions,
  LitPropsLowerOptions,
  LitResumableOptions,
  LitWebpackPluginOptions,
  MemoizeOptions,
  PropsLowerOptions,
  ResumableOptions,
} from './options.js';
export {
  CssFuseWebpackPlugin,
  CssMinifierWebpackPlugin,
  cssFuse,
  cssMinifier,
  DirectivesWebpackPlugin,
  DirtyMaskWebpackPlugin,
  DomPathsWebpackPlugin,
  directives,
  dirtyMask,
  domPaths,
  ElemProxyWebpackPlugin,
  EventHoistWebpackPlugin,
  elemProxy,
  eventHoist,
  HtmlAotWebpackPlugin,
  HtmlFuseWebpackPlugin,
  HtmlMinifierWebpackPlugin,
  htmlAot,
  htmlFuse,
  htmlMinifier,
  LitWebpackPlugin,
  lit,
  lit as default,
  litCore,
  litCssFuse,
  litCssMinifier,
  litDirectives,
  litDirtyMask,
  litDomPaths,
  litElemProxy,
  litEventHoist,
  litHtmlAot,
  litHtmlFuse,
  litHtmlMinifier,
  litMemoize,
  litPropsLower,
  litResumable,
  MemoizeWebpackPlugin,
  memoize,
  PropsLowerWebpackPlugin,
  propsLower,
  ResumableWebpackPlugin,
  resumable,
} from './plugin.js';
