/// <reference types="node" />

export {
  default as litWebpackLoader,
  getPluginState,
  registerPluginState,
  unregisterPluginState,
} from './loader.js';
export type {
  CssFuseOptions,
  CssMinifierOptions,
  HtmlAotOptions,
  HtmlFuseOptions,
  HtmlMinifierOptions,
  LitCorePluginOptions,
  LitCssFuseOptions,
  LitCssMinifierOptions,
  LitHtmlAotOptions,
  LitHtmlFuseOptions,
  LitHtmlMinifierOptions,
  LitPluginOptions,
  LitPropsLowerOptions,
  LitWebpackPluginOptions,
  PropsLowerOptions,
} from './options.js';
export {
  CssFuseWebpackPlugin,
  CssMinifierWebpackPlugin,
  cssFuse,
  cssMinifier,
  HtmlAotWebpackPlugin,
  htmlAot,
  HtmlFuseWebpackPlugin,
  htmlFuse,
  HtmlMinifierWebpackPlugin,
  htmlMinifier,
  LitWebpackPlugin,
  lit,
  lit as default,
  litCore,
  litCssFuse,
  litCssMinifier,
  litHtmlAot,
  litHtmlFuse,
  litHtmlMinifier,
  litPropsLower,
  PropsLowerWebpackPlugin,
  propsLower,
} from './plugin.js';
